### ISSUE TITLE
Play video in external storage

### ISSUE THREAD

**Issue by safaldas** [jepiqueau/capacitor-video-player#5]
I have a video that is dowloaded to the external storage in the path `/storage/emulated/0/Android/data/org.cordova.quasar.app/files/downloads/ppi_demo/ppi_demo_1.mp4` how to play this file.

**Comment by jepiqueau** [comment]
@safadas i didn't forget your question. i was engaged in a complete refurbishing of my web components and  my capacitor plugins to propose them in libraries. This is going to be deprecated, visit @jeepq/capacitor for new releases of this plugin. this issue is not yet fixed. So please can you reopen it over there thanks

**Comment by jepiqueau** [comment]
@safaldas i got a new release **capacitor-video-player 2.3.0-beta.4** where i have implemented  the selection of video from the internal storage gallery Can you try it and tell me if it suit your need
