### ISSUE TITLE
how can we have a quality selector for hls video

### ISSUE THREAD

**Issue by kannanvrn** [jepiqueau/capacitor-video-player#60]
@jepiqueau 
I would like to thank you for this package. 
i use hls video format as source. I would like to have a quality selector in the player. Based upon which quality is selected from the hls source, player would be able to  pull video from that as is other normal players.
![image](https://user-images.githubusercontent.com/65075379/141052454-e24baab6-2083-45a3-806d-f9dafc055cbb.png)

**Comment by jepiqueau** [comment]
@kannanvrn thanks for using the player.which platform are you using Web, Android or iOS. Can you give me an example of this selector if it is existing on the Web

**Comment by jepiqueau** [comment]
@kannanvrn i had a quick look over the web, it seems not to be  a recommended approach to do this as the player will adjust the quality by itself because HLS is an adaptive stream that adjusts its quality depending on the available bandwidth. It seems also that it will bring a lot of complexity in each of the players i am using (AVPlayer for iOS, Exoplayer for Android and hls.js for Web). So i am not sure i will go that way.

**Comment by kannanvrn** [comment]
> @kannanvrn i had a quick look over the web, it seems not to be a recommended approach to do this as the player will adjust the quality by itself because HLS is an adaptive stream that adjusts its quality depending on the available bandwidth. It seems also that it will bring a lot of complexity in each of the players i am using (AVPlayer for iOS, Exoplayer for Android and hls.js for Web). So i am not sure i will go that way.

ok @jepiqueau  . Thank You for your reply. I can understand. Am closing this issue.
